<?php

function cipher_menu(){
    $items = array();
    $items['encryption_form'] = array(
        'title' => 'Encryption Form',
        'page callback' => 'cipher_form',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['encryption_success'] = array(
        'title' => 'Encryption Success',
        'page callback' => 'cipher_result',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function cipher_form(){
    return 'hello';
}

function cipher_results(){
    return 'goodbye';
}
