<?php

function cipher_menu(){
    $items = array();
    $items['encryption_form'] = array(
        'title' => 'Encryption Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['encryption_success'] = array(
        'title' => 'Encryption Success',
        'page callback' => 'cipher_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form(){
    $form = array();
    $form['shift_value'] = [
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('The shift value is the number of places to shift each letter along the alphebet. It must be a number.'),
    ];
    $form['direction'] = [
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('The shift direction can be "right" or "left" and is the direction the cipher moves in.'),
    ];
    $form['phrase'] = [
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('The Phrase is your text to be encrypted. It must only be letters and punctuation'),
    ];
    $form['submit'] = [
        '#type' => 'submit',
        '#value' => 'Encrypt',
    ];
    return $form;
}

// I chose to encrypt the information in the submit because it did not
// feel right to pass the un-encrypted variables into the session.
function cipher_form_submit($form, &$form_state){
    $value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];

    $_SESSION['result'] = $value . " " . $direction . " " . $phrase;

    $form_state['redirect'] = 'encryption_success';
}

function cipher_result(){
    $result = $_SESSION['result'];

    return $result;
}
